# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: ish group
email: info@ish.com.au
description: >
  ish onCourse. The most comprehensive and easy to use, marketing and enrolment system available.
baseurl: ""
url: "https://www.ish.com.au"

markdown: kramdown
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']